sudo: required
dist: trusty

install:
  - sudo apt-get update -qq
  - sudo apt-get install liblapack-dev

cache:
  directories:
    - $HOME/dependencies

language:
  - python
  - cpp

os:
  - linux
  # - osx

python:
  - 3.4

before_install:
  # - echo "HOME is in: " $HOME  # this is giving a YAML error (?)
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - ulimit -s 32768  # C++ compilers require a lot of memory

  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n shyft_env python=$TRAVIS_PYTHON_VERSION pyyaml numpy libgfortran netcdf4 gdal matplotlib requests nose coverage pip shapely pyproj swig
  - source activate shyft_env
  #- conda install -c https://conda.anaconda.org/minrk swig  # hits a bug in conda
  #- conda install swig
  - pip install descartes
  - python -V

  # The data repository dependency
  - git clone --depth=50 --branch=master https://github.com/statkraft/shyft-data.git shyft-data
  - ln -s `pwd`/shyft-data ../shyft-data  # make it visible to the test suite of shyft

#compiler:
#  - gcc
#  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j 2 VERBOSE=1  # 2 paralel g++ process should take up to 3.5 GB RAM!
  - export LD_LIBRARY_PATH=$HOME/dependencies/local/lib
  - make test
  - make install
  - PYTHONPATH=.. python -c"import shyft; shyft.print_versions()"
  - nosetests ..

notifications:
  email: false
