model: !!python/name:api.FullPTGSKModel
bounding_box:
    - 0.0
    - 50000.0
    - 0.0
    - 100000.0
cell_dx: 1000.0
cell_dy: 1000.0
input_source_repository:
    type: !!python/name:orchestration.repository.testsupport.mocks.MockInputSourceRepository
    args: null
state_repository:
    type: !!python/name:orchestration.repository.testsupport.mocks.MockStateRepository
    args: null
cell_repository:
    type: !!python/name:orchestration.repository.testsupport.mocks.MockCellReadOnlyRepository
    args: null
parameters:
    albedo: 0.2
    alpha: 1.26
    winter_end_day_of_year: 100
    snow_tx: -0.5
    wind_scale: 2.0
    wind_const: 1.0
    max_water: 0.1
    surface_magnitude: 30.0
    max_albedo: 0.9
    min_albedo: 0.6
    fast_albedo_decay_rate: 5.0
    slow_albedo_decay_rate: 5.0
    snowfall_reset_depth: 5.0
    glacier_albedo: 0.4
    calculate_iso_pot_energy: false
    ae_scale_factor: 1.5
    btk_gradient_sd: 0.25
    btk_gradient: -0.6
    btk_sill: 25.0
    btk_nugget: 0.5
    btk_range: 200000.0
    btk_zscale: 20.0
    idw_max_members: 10
    idw_max_distance: 200000.0
    idw_precipitation_gradient: 2.0
    constant_wind_speed: 2.0
    constant_relative_humidity: 0.7
